Hw15 calendar
AZhur771/otus-go-homework pull request #15
Opened 2022-11-09 20:13 UTC by AZhur771

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make integration-tests`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

2022-11-13 11:47 UTC, dshemin requested changes

2022-11-13 11:47 UTC, dshemin commented on hw12_13_14_15_calendar/build/calendar/Dockerfile
> +CMD ${BIN_FILE_GOOSE} -dir ./migrations up && ${BIN_FILE} -config ${CONFIG_FILE}
Не лучшее решение запускать миграции внутри контейнере. Представьте, что мы будет раскатывать наше приложение в kubernetes или любом другом оркестраторе. И мы будем раскатывать с количеством реплик более 1. В такой ситуации мы получим следующее: нашу базу начнёт мигрировать практически одновременно несколько разных процессов.

2022-11-13 11:47 UTC, dshemin commented on hw12_13_14_15_calendar/build/calendar_migrator/Dockerfile
> +LABEL SERVICE="calendar-scheduler"
Тут ошибочная метка. Это контейнер с миграцией, а не шедулером.

2022-11-13 11:47 UTC, dshemin commented on hw12_13_14_15_calendar/build/calendar_scheduler/Dockerfile
> +ENV BIN_FILE /opt/calendar/calendar-scheduler-app
Нам точно нужна эта переменная окружения тут?

2022-11-13 11:47 UTC, dshemin commented on hw12_13_14_15_calendar/build/calendar_sender/Dockerfile
> +ENV BIN_FILE /opt/calendar/calendar-sender-app
Нам точно нужна эта переменная окружения тут?

2022-11-13 11:47 UTC, dshemin commented on hw12_13_14_15_calendar/internal/scheduler/scheduler.go
> +		if s.startImmediate {
Давайте развернём логику если `s.startImmediate == true`.
1.  Мы попадаем в этот цикл, видим что `s.startImmediate == true`, сканируем и отправляем
2. Блокируемся в селекте
3. Проходит `s.scanPeriod` время и мы сканируем и отправляем
4. Возвращаемся в начало цикла.
5. Видим что `s.startImmediate == true`, сканируем и отправляем
...

Итого: у нас получается что после первой итерации мы всегда будем пытаться найти события и их отправить дважды. Учитывая что скорее всего мы не найдём никаких событий - мы сделаем один ненужный запрос.

2022-11-13 11:47 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err != nil {
Если мы не собираемся добавлять контекста к ошибке, то лучше просто сразу вернуть ошибку:
```
_, err := s.db.ExecContext()
return err
```

2022-11-13 16:18 UTC, AZhur771 commented on hw12_13_14_15_calendar/build/calendar/Dockerfile
> +CMD ${BIN_FILE_GOOSE} -dir ./migrations up && ${BIN_FILE} -config ${CONFIG_FILE}
Как тогда лучше поступить? Поднимать отдельный контейнер для миграций?

2022-11-13 16:18 UTC, AZhur771 commented on hw12_13_14_15_calendar/build/calendar_migrator/Dockerfile
> +LABEL SERVICE="calendar-scheduler"
Да, ошибся

2022-11-14 13:37 UTC, dshemin approved these changes

2022-11-14 14:15 UTC, merged